### PR TITLE
Task 2

### PR DESCRIPTION
**Pull request by badjaaga**
Task: https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/2_serving_spa/task.md

What was done: 
2.1 deployment in s3 bucket and cloudfront distribution 
https://d1xuskap4uvfo1.cloudfront.net/
https://web-cars-marketplace-angular.s3.eu-west-1.amazonaws.com/
2.2 added serverless-s3-sync and serverless-single-page-app with configuration to deploy static website automatically

Estimated mark: 90 (403 issue with s3 permissions did not solved)

### CODE REVIEW

**Comment by Inga-Vishnivetskaia** [comment]
Hello! :star: Could you please maybe update the serverless.yml and package.json (by integrating the Serverless-finch and serverless-single-page-app) in order to use auto build, deploy and CloudFront invalidation? Now if I understood correctly s3-sync makes only auto deploy to S3 bucket and CloudFront invalidation has to be manual? :pensive:

**Comment by badjaaga** [comment]
@Inga-Vishnivetskaia thanks for notifying me. Of course, that makes sense. I've changed serverless.yml file and add plugin to verify and deploy changes on CloudFront.

**Comment by Inga-Vishnivetskaia** [comment]
Hello! Could you please add a link for the CloudFront auto deployed app to the readme? thank you

**Comment by badjaaga** [comment]
https://github.com/badjaaga/aws-course-fe/pull/1/commits/64b221b26dc20cb51a3ca674753cf61a7fbcaab8

**Pull request merged**
